CREATE TABLE promotion (
                           id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nom VARCHAR(100) NOT NULL,
                           CONSTRAINT uk_promotion_nom UNIQUE (nom)
);

CREATE TABLE etudiant (
                          id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nom          VARCHAR(120) NOT NULL,
                          promotion_id BIGINT NOT NULL,
                          CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);
CREATE INDEX idx_etudiant_promotion ON etudiant (promotion_id);

CREATE TABLE session_cours (
                               id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               titre         VARCHAR(200) NOT NULL,
                               promotion_id  BIGINT NOT NULL,
                               code          VARCHAR(6) NOT NULL,
                               ouverture_at  TIMESTAMP WITH TIME ZONE NOT NULL,
                               expiration_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               statut        VARCHAR(10) NOT NULL,
                               cloture_at    TIMESTAMP WITH TIME ZONE,
                               CONSTRAINT uk_session_code UNIQUE (code),                                -- RG17
                               CONSTRAINT ck_session_statut CHECK (statut IN ('OUVERTE', 'CLOTUREE')),  -- RG14
                               CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion (id)
);
CREATE INDEX idx_session_promotion ON session_cours (promotion_id);

CREATE TABLE presence (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          session_id  BIGINT NOT NULL,
                          etudiant_id BIGINT NOT NULL,
                          source      VARCHAR(10) NOT NULL,
                          marquee_at  TIMESTAMP WITH TIME ZONE NOT NULL,
                          CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id), -- RG18
                          CONSTRAINT ck_presence_source CHECK (source IN ('ETUDIANT', 'FORMATEUR')), -- RG13
                          CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
                          CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);
CREATE INDEX idx_presence_etudiant ON presence (etudiant_id);

CREATE TABLE exercice (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          session_id  BIGINT NOT NULL,
                          etudiant_id BIGINT NOT NULL,
                          lien        VARCHAR(500) NOT NULL,
                          statut      VARCHAR(20) NOT NULL,
                          depose_at   TIMESTAMP WITH TIME ZONE NOT NULL,
                          modifie_at  TIMESTAMP WITH TIME ZONE,
                          CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id), -- RG19
                          CONSTRAINT ck_exercice_statut CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'NOTE')),
                          CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session_cours (id),
                          CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)
);
CREATE INDEX idx_exercice_etudiant ON exercice (etudiant_id);

CREATE TABLE relecture (
                           id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           exercice_id  BIGINT NOT NULL,
                           relecteur_id BIGINT NOT NULL,
                           note         INTEGER,
                           commentaire  VARCHAR(2000),
                           attribuee_at TIMESTAMP WITH TIME ZONE NOT NULL,
                           rendue_at    TIMESTAMP WITH TIME ZONE,   -- NULL = assignee (RG6), renseigne = rendue
                           CONSTRAINT uk_relecture_exercice UNIQUE (exercice_id),      -- RG5
                           CONSTRAINT ck_relecture_note CHECK (note BETWEEN 0 AND 20), -- RG8
                           CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice (id),
                           CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant (id)
);
CREATE INDEX idx_relecture_relecteur ON relecture (relecteur_id);